// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package ai_metathings_component_service_joker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadFileRequest struct {
	Streaming            *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Source               *wrappers.StringValue `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *wrappers.StringValue `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UploadFileRequest) Reset()         { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()    {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *UploadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileRequest.Unmarshal(m, b)
}
func (m *UploadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileRequest.Marshal(b, m, deterministic)
}
func (m *UploadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileRequest.Merge(m, src)
}
func (m *UploadFileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadFileRequest.Size(m)
}
func (m *UploadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileRequest proto.InternalMessageInfo

func (m *UploadFileRequest) GetStreaming() *wrappers.BoolValue {
	if m != nil {
		return m.Streaming
	}
	return nil
}

func (m *UploadFileRequest) GetSource() *wrappers.StringValue {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *UploadFileRequest) GetDestination() *wrappers.StringValue {
	if m != nil {
		return m.Destination
	}
	return nil
}

type DownloadFileRequest struct {
	Streaming            *wrappers.BoolValue   `protobuf:"bytes,1,opt,name=streaming,proto3" json:"streaming,omitempty"`
	Source               *wrappers.StringValue `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *wrappers.StringValue `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DownloadFileRequest) Reset()         { *m = DownloadFileRequest{} }
func (m *DownloadFileRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadFileRequest) ProtoMessage()    {}
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *DownloadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileRequest.Unmarshal(m, b)
}
func (m *DownloadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileRequest.Marshal(b, m, deterministic)
}
func (m *DownloadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileRequest.Merge(m, src)
}
func (m *DownloadFileRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadFileRequest.Size(m)
}
func (m *DownloadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileRequest proto.InternalMessageInfo

func (m *DownloadFileRequest) GetStreaming() *wrappers.BoolValue {
	if m != nil {
		return m.Streaming
	}
	return nil
}

func (m *DownloadFileRequest) GetSource() *wrappers.StringValue {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *DownloadFileRequest) GetDestination() *wrappers.StringValue {
	if m != nil {
		return m.Destination
	}
	return nil
}

func init() {
	proto.RegisterType((*UploadFileRequest)(nil), "ai.metathings.component.service.joker.UploadFileRequest")
	proto.RegisterType((*DownloadFileRequest)(nil), "ai.metathings.component.service.joker.DownloadFileRequest")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0x42, 0xc1, 0x69, 0x3d, 0xb8, 0x82, 0x94, 0x28, 0x22, 0x01, 0xc1, 0xd3, 0x16,
	0xaa, 0x87, 0xe2, 0xc1, 0x83, 0xa8, 0x07, 0x8f, 0x2d, 0x7a, 0x76, 0x9b, 0x8c, 0x71, 0x35, 0xd9,
	0x59, 0x77, 0x27, 0x16, 0x9f, 0x4f, 0x7c, 0x05, 0x9f, 0x47, 0x9a, 0xb5, 0xb4, 0x18, 0x85, 0x5c,
	0xbd, 0xee, 0xfc, 0xdf, 0x3f, 0x3b, 0xf3, 0x0f, 0x6c, 0x79, 0x74, 0xaf, 0x3a, 0x45, 0x69, 0x1d,
	0x31, 0x89, 0x23, 0xa5, 0x65, 0x89, 0xac, 0xf8, 0x51, 0x9b, 0xdc, 0xcb, 0x94, 0x4a, 0x4b, 0x06,
	0x0d, 0xcb, 0x85, 0xec, 0x89, 0x9e, 0xd1, 0xc5, 0x07, 0x39, 0x51, 0x5e, 0xe0, 0xa0, 0x86, 0xa6,
	0xd5, 0xc3, 0x60, 0xe6, 0x94, 0xb5, 0xe8, 0x7c, 0xb0, 0x89, 0xf7, 0x7e, 0xd6, 0xb1, 0xb4, 0xfc,
	0x16, 0x8a, 0xc9, 0x7b, 0x04, 0xdb, 0xb7, 0xb6, 0x20, 0x95, 0x5d, 0xeb, 0x02, 0xc7, 0xf8, 0x52,
	0xa1, 0x67, 0x31, 0x82, 0x4d, 0xcf, 0x0e, 0x55, 0xa9, 0x4d, 0xde, 0x8f, 0x0e, 0xa3, 0xe3, 0xee,
	0x30, 0x96, 0xc1, 0x46, 0x2e, 0x6c, 0xe4, 0x05, 0x51, 0x71, 0xa7, 0x8a, 0x0a, 0xc7, 0x4b, 0xb1,
	0x38, 0x85, 0x8e, 0xa7, 0xca, 0xa5, 0xd8, 0x5f, 0xaf, 0xb1, 0xfd, 0x06, 0x36, 0x61, 0xa7, 0x4d,
	0x1e, 0xc0, 0x6f, 0xad, 0x38, 0x87, 0x6e, 0x86, 0x9e, 0xb5, 0x51, 0xac, 0xc9, 0xf4, 0x37, 0x5a,
	0xa0, 0xab, 0x40, 0xf2, 0x11, 0xc1, 0xce, 0x25, 0xcd, 0xcc, 0x3f, 0x9f, 0x63, 0xf8, 0x19, 0x41,
	0xef, 0x66, 0x1e, 0xea, 0x24, 0x24, 0x2c, 0xee, 0x01, 0x96, 0xe9, 0x88, 0x91, 0x6c, 0x75, 0x11,
	0xb2, 0x11, 0x68, 0xbc, 0xdb, 0xf8, 0xc3, 0xd5, 0xfc, 0x08, 0x92, 0x35, 0x91, 0x41, 0x6f, 0x75,
	0x73, 0xe2, 0xac, 0x65, 0x8f, 0x5f, 0xd6, 0xfd, 0x77, 0x97, 0x69, 0xa7, 0x7e, 0x39, 0xf9, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x55, 0xe9, 0xf1, 0xbf, 0xe2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JokerServiceClient is the client API for JokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JokerServiceClient interface {
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type jokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewJokerServiceClient(cc *grpc.ClientConn) JokerServiceClient {
	return &jokerServiceClient{cc}
}

func (c *jokerServiceClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ai.metathings.component.service.joker.JokerService/UploadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jokerServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ai.metathings.component.service.joker.JokerService/DownloadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JokerServiceServer is the server API for JokerService service.
type JokerServiceServer interface {
	UploadFile(context.Context, *UploadFileRequest) (*empty.Empty, error)
	DownloadFile(context.Context, *DownloadFileRequest) (*empty.Empty, error)
}

// UnimplementedJokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJokerServiceServer struct {
}

func (*UnimplementedJokerServiceServer) UploadFile(ctx context.Context, req *UploadFileRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (*UnimplementedJokerServiceServer) DownloadFile(ctx context.Context, req *DownloadFileRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}

func RegisterJokerServiceServer(s *grpc.Server, srv JokerServiceServer) {
	s.RegisterService(&_JokerService_serviceDesc, srv)
}

func _JokerService_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokerServiceServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.component.service.joker.JokerService/UploadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokerServiceServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JokerService_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokerServiceServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.metathings.component.service.joker.JokerService/DownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokerServiceServer).DownloadFile(ctx, req.(*DownloadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ai.metathings.component.service.joker.JokerService",
	HandlerType: (*JokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadFile",
			Handler:    _JokerService_UploadFile_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _JokerService_DownloadFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
