// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package ai_metathings_component_service_joker

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/golang/protobuf/ptypes/empty"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *UploadFileRequest) Validate() error {
	if this.Streaming != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Streaming); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Streaming", err)
		}
	}
	if this.Source != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Source); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Source", err)
		}
	}
	if this.Destination != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Destination); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Destination", err)
		}
	}
	return nil
}
func (this *DownloadFileRequest) Validate() error {
	if this.Streaming != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Streaming); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Streaming", err)
		}
	}
	if this.Source != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Source); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Source", err)
		}
	}
	if this.Destination != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Destination); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Destination", err)
		}
	}
	return nil
}
